const BIAS_CONFIG = {
  Low:      { color: "#34d399", bg: "rgba(52,211,153,0.1)",  border: "rgba(52,211,153,0.3)",  label: "Low Bias" },
  Moderate: { color: "#fbbf24", bg: "rgba(251,191,36,0.1)",  border: "rgba(251,191,36,0.3)",  label: "Moderate Bias" },
  High:     { color: "#f97316", bg: "rgba(249,115,22,0.1)",  border: "rgba(249,115,22,0.3)",  label: "High Bias" },
  Severe:   { color: "#f75555", bg: "rgba(247,85,85,0.1)",   border: "rgba(247,85,85,0.3)",   label: "Severe Bias" },
};

const BAR_COLORS = ["#4f8ef7", "#7c5cfc", "#00d4a8", "#fbbf24", "#f97316", "#f75555"];

function StatCard({ label, value, sub, color }) {
  return (
    <div style={{ background: "var(--card)", border: `1px solid ${color ? color + "44" : "var(--border)"}`, borderRadius: "var(--radius2)", padding: "1.25rem 1.5rem", position: "relative", overflow: "hidden" }}>
      {color && <div style={{ position: "absolute", top: 0, left: 0, right: 0, height: 3, background: color, borderRadius: "12px 12px 0 0" }} />}
      <div style={{ fontSize: 11, fontWeight: 700, color: "var(--text3)", letterSpacing: "0.08em", textTransform: "uppercase", marginBottom: 8 }}>{label}</div>
      <div style={{ fontSize: 32, fontWeight: 700, color: color || "var(--text)", letterSpacing: "-1px", lineHeight: 1 }}>{value}</div>
      {sub && <div style={{ fontSize: 12, color: "var(--text2)", marginTop: 6 }}>{sub}</div>}
    </div>
  );
}

function BarChart({ data }) {
  const max = Math.max(...Object.values(data), 1);
  const entries = Object.entries(data).sort((a, b) => b[1] - a[1]);
  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
      {entries.map(([group, rate], i) => (
        <div key={group}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline", marginBottom: 6 }}>
            <span style={{ fontSize: 13, fontWeight: 600, color: "var(--text)" }}>{group}</span>
            <span style={{ fontSize: 13, fontFamily: "var(--mono)", color: BAR_COLORS[i % BAR_COLORS.length], fontWeight: 600 }}>{rate.toFixed(1)}%</span>
          </div>
          <div style={{ height: 8, background: "var(--bg3)", borderRadius: 4, overflow: "hidden" }}>
            <div style={{ height: "100%", width: `${(rate / max) * 100}%`, background: BAR_COLORS[i % BAR_COLORS.length], borderRadius: 4, transition: "width 1s cubic-bezier(0.4,0,0.2,1)" }} />
          </div>
        </div>
      ))}
    </div>
  );
}

export default function ResultsStep({ results, config, onReset, onBack }) {
  const bc = BIAS_CONFIG[results.bias_level] || BIAS_CONFIG.Low;
  const di = results.disparate_impact;
  const diPct = Math.round(di * 100);

  const downloadReport = () => {
    const txt = `NyayAI Bias Report\n${"=".repeat(40)}\n\nAttribute: ${results.attribute}\nOutcome column: ${config.outcomeCol}\nBias level: ${results.bias_level}\nDisparate impact: ${results.disparate_impact}\nMax approval gap: ${results.demographic_parity_diff}%\nTotal records: ${results.total_rows}\n\nApproval rates:\n${Object.entries(results.approval_rates).map(([g,r]) => `  ${g}: ${r}%`).join("\n")}\n\nGroup sizes:\n${Object.entries(results.groups).map(([g,c]) => `  ${g}: ${c} records`).join("\n")}\n\nGemini AI explanation:\n${results.ai_explanation}\n\nGenerated by NyayAI — AI Bias Auditor for India`;
    const a = document.createElement("a");
    a.href = URL.createObjectURL(new Blob([txt], { type: "text/plain" }));
    a.download = `nyayai-bias-report-${results.attribute}-${Date.now()}.txt`;
    a.click();
  };

  return (
    <div>
      {/* Header */}
      <div className="fade-up" style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", flexWrap: "wrap", gap: 16, marginBottom: "2rem" }}>
        <div>
          <div style={{ display: "inline-flex", alignItems: "center", gap: 8, background: bc.bg, border: `1px solid ${bc.border}`, borderRadius: 20, padding: "5px 14px", fontSize: 13, fontWeight: 700, color: bc.color, marginBottom: 12 }}>
            <div style={{ width: 8, height: 8, borderRadius: "50%", background: bc.color, boxShadow: `0 0 8px ${bc.color}` }} />
            {bc.label} Detected
          </div>
          <h2 style={{ fontSize: 28, fontWeight: 700, letterSpacing: "-0.5px", marginBottom: 6 }}>Bias Analysis Report</h2>
          <p style={{ color: "var(--text2)", fontSize: 14 }}>
            Testing <span style={{ color: "var(--accent)", fontWeight: 600, fontFamily: "var(--mono)" }}>{results.attribute}</span> → <span style={{ color: "var(--accent)", fontWeight: 600, fontFamily: "var(--mono)" }}>{config.outcomeCol}</span> across <strong>{results.total_rows}</strong> records
          </p>
        </div>
        <div style={{ display: "flex", gap: 8 }}>
          <button onClick={downloadReport} style={{ padding: "10px 18px", borderRadius: "var(--radius)", fontSize: 13, fontWeight: 600, background: "var(--card2)", color: "var(--text2)", border: "1px solid var(--border)" }}>
            ↓ Download
          </button>
        </div>
      </div>

      {/* Stat cards */}
      <div className="fade-up-1" style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 14, marginBottom: "2rem" }}>
        <StatCard label="Disparate impact" value={di.toFixed(2)} sub={di >= 0.8 ? "✓ Passes 80% rule" : "✗ Fails 80% rule"} color={di >= 0.8 ? "#34d399" : di >= 0.6 ? "#f97316" : "#f75555"} />
        <StatCard label="Max approval gap" value={`${results.demographic_parity_diff.toFixed(1)}%`} sub="Between highest & lowest group" color={results.demographic_parity_diff <= 5 ? "#34d399" : results.demographic_parity_diff <= 15 ? "#fbbf24" : "#f75555"} />
        <StatCard label="Groups analyzed" value={Object.keys(results.groups).length} sub={`${results.total_rows} total records`} />
      </div>

      {/* Two column layout */}
      <div className="fade-up-2" style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16, marginBottom: "1.5rem" }}>
        {/* Bar chart */}
        <div style={{ background: "var(--card)", border: "1px solid var(--border)", borderRadius: "var(--radius2)", padding: "1.5rem" }}>
          <div style={{ fontSize: 13, fontWeight: 700, color: "var(--text2)", marginBottom: 4, letterSpacing: "0.05em", textTransform: "uppercase" }}>Approval rate by {results.attribute}</div>
          <div style={{ fontSize: 11, color: "var(--text3)", marginBottom: 20 }}>For outcome = "{config.positiveOutcome}"</div>
          <BarChart data={results.approval_rates} />
          <div style={{ marginTop: 20, padding: "10px 14px", background: "var(--bg3)", borderRadius: "var(--radius)", fontSize: 12 }}>
            <span style={{ color: "var(--text3)" }}>80% rule score: </span>
            <span style={{ fontWeight: 700, color: di >= 0.8 ? "#34d399" : "#f75555", fontFamily: "var(--mono)" }}>{diPct}%</span>
            <span style={{ color: "var(--text3)" }}> (min: 80%)</span>
          </div>
        </div>

        {/* Group sizes */}
        <div style={{ background: "var(--card)", border: "1px solid var(--border)", borderRadius: "var(--radius2)", padding: "1.5rem" }}>
          <div style={{ fontSize: 13, fontWeight: 700, color: "var(--text2)", marginBottom: 4, letterSpacing: "0.05em", textTransform: "uppercase" }}>Sample sizes</div>
          <div style={{ fontSize: 11, color: "var(--text3)", marginBottom: 20 }}>Records per group</div>
          <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
            {Object.entries(results.groups).sort((a, b) => b[1] - a[1]).map(([group, count], i) => (
              <div key={group} style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
                <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                  <div style={{ width: 10, height: 10, borderRadius: "50%", background: BAR_COLORS[i % BAR_COLORS.length] }} />
                  <span style={{ fontSize: 13, color: "var(--text)" }}>{group}</span>
                </div>
                <span style={{ fontFamily: "var(--mono)", fontSize: 13, fontWeight: 600, color: "var(--text2)", background: "var(--bg3)", padding: "2px 10px", borderRadius: 6 }}>{count}</span>
              </div>
            ))}
          </div>

          {/* Metrics legend */}
          <div style={{ marginTop: 24, paddingTop: 16, borderTop: "1px solid var(--border)", fontSize: 12, color: "var(--text3)", lineHeight: 1.8 }}>
            <div><span style={{ color: "#34d399", fontWeight: 600 }}>Low</span> = DI ≥ 0.9 & gap ≤ 5%</div>
            <div><span style={{ color: "#fbbf24", fontWeight: 600 }}>Moderate</span> = DI ≥ 0.8 & gap ≤ 15%</div>
            <div><span style={{ color: "#f97316", fontWeight: 600 }}>High</span> = DI ≥ 0.6</div>
            <div><span style={{ color: "#f75555", fontWeight: 600 }}>Severe</span> = DI &lt; 0.6</div>
          </div>
        </div>
      </div>

      {/* AI Explanation */}
      <div className="fade-up-3" style={{ background: "var(--card)", border: `1px solid ${bc.border}`, borderRadius: "var(--radius2)", padding: "1.5rem", marginBottom: "2rem", position: "relative", overflow: "hidden" }}>
        <div style={{ position: "absolute", top: 0, left: 0, right: 0, height: 3, background: `linear-gradient(90deg, ${bc.color}, transparent)` }} />
        <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 14 }}>
          <div style={{ width: 32, height: 32, borderRadius: 10, background: "linear-gradient(135deg, #4285f4, #0f9d58)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 16 }}>G</div>
          <div>
            <div style={{ fontWeight: 700, fontSize: 14 }}>Gemini AI Explanation</div>
            <div style={{ fontSize: 11, color: "var(--text3)" }}>in {config.language}</div>
          </div>
        </div>
        <p style={{ fontSize: 15, color: "var(--text)", lineHeight: 1.8, fontWeight: 300 }}>{results.ai_explanation}</p>
      </div>

      {/* Action buttons */}
      <div className="fade-up-4" style={{ display: "flex", gap: 12 }}>
        <button onClick={onBack} style={{ padding: "12px 24px", borderRadius: "var(--radius)", fontSize: 14, fontWeight: 500, background: "var(--card2)", color: "var(--text2)", border: "1px solid var(--border)" }}>
          ← Change config
        </button>
        <button onClick={onReset} style={{ flex: 1, padding: "12px 24px", borderRadius: "var(--radius)", fontSize: 14, fontWeight: 700, background: "linear-gradient(135deg, var(--accent), var(--accent2))", color: "#fff", boxShadow: "0 4px 20px rgba(79,142,247,0.35)" }}>
          Analyze another dataset →
        </button>
      </div>
    </div>
  );
}
